### ISSUE TITLE
Split packages to 'shared' containing binaries and 'configurations' that contains related configurations

### ISSUE THREAD

**Issue by mkl-eea-sk** [UnifiedViews/Packages#14]
Consider creating .deb package ```unifiedviews-core-commons``` which would contain common changes, for example it should handle SQL database schema updates. Then, the ```unifiedviews-backend``` and ```unifiedviews-webapp``` should depend on this new package.
Also the ```unifiedviews-core-plugins``` package should depend on the commons one, not frontend, nor backend.

**Comment by skrchnavy** [comment]
Update of this requirement due to support of mysql and pgsql:
Currently there is ```unifiedviews-backend``` and ```unifiedviews-webapp```. New structure to be defined:
* ```unifiedviews-backend-shared```containing only data
  * ```unifiedviews-backend-mysql``` containing configuration and control scripts related to mysql support, depends on ```unifiedviews-backend-shared``` amd ```mysql```
  * ```unifiedviews-backend-pgsql``` containing configuration and control scripts related to pgsql support, depends on ```unifiedviews-backend-shared``` amd ```pgsql```
    * ```unifiedviews-backend``` metapackage depends on ```unifiedviews-backend-mysql```or ```unifiedviews-backend-pgsql```
* ```unifiedviews-webapp-shared``` containing only data
  * ```unifiedviews-backend-mysql``` containing configuration and control scripts related to mysql support, depends on ```unifiedviews-webapp-shared``` amd ```mysql```
  * ```unifiedviews-webapp-pgsql``` containing configuration and control scripts related to pgsql support, depends on ```unifiedviews-webapp-shared``` amd ```pgsql```
    * ```unifiedviews-webapp``` metapackage depends on ```unifiedviews-webapp-mysql```or ```unifiedviews-webapp-pgsql```
